### ISSUE TITLE
about remote parameter match at app.use function, :id can't match

### ISSUE THREAD

**Issue by neosxu** [senchalabs/connect#1075]
dear author:
      i'm a new learner for connect .when i use the code like below:
//==========================================
  var user = require('controls/user');
  app.use('/user/:id', user.get);
  app.use('/userlist', user.list);
  app.use('/', PageIndex);
//===========================================
and i request at the url address: localhost:3000/user/1  , but the function PageIndex was responsed.
why can't match the route parameter with varient like :id , and how should i do?

i look up the source code of connect index.js  at the function handle line 160 
//==============================================
// skip this layer if the route doesn't match
    if (path.toLowerCase().substr(0, route.length) !== route.toLowerCase()) {
      return next(err);
    }
//==============================================
that match maybe not support regex string match ?

but at express module , we can use like this:
//===============================================
app.get('/login/:id', urlencodedParser, function (req, res) {
  console.log('Function login id invoke');
  res.send('welcome, ' + req.url)
})
//===============================================

please help , how to do match the route parmater with varient like :id , :name ?
thank you !

**Comment by dougwilson** [comment]
Hi! You may very well be confusing Express with this module, which is Connect. The biggest difference is that Connect does not take parameters like `':id'`; all paths are _literal only_.

What this means is that `app.use('/user/:id')` will never match `/user/42`, since that doesn't contain the literal characters `:id` in the URL; it only matches URLs that start with `"/user/:id"`.

Connect itself is the very core, which means it doesn't do much besides chain middleware together. Express is where you can get parametrized paths like you are looking for.

**Comment by neosxu** [comment]
thank you, i like the design idea with middware like plugs. if anyother connect route i can use to reslove this problem?

**Comment by dougwilson** [comment]
Hm, I'm not 100% sure what you mean. Typically if you want to use things like `:id` you'd have to use Express or similar. Is there a reason why you wouldn't be Express? That may help me determine what would be the best fit for your use-case.

**Comment by neosxu** [comment]
yes  thank you, you can close this issue, i can use express module with varient :id at route parameter, and the express module is also support middware.
