### ISSUE TITLE
app.listen not documented

### ISSUE THREAD

**Issue by zodiac** [senchalabs/connect#1088]
The only documentation I can find for `app.listen` is this section in the README

![image](https://cloud.githubusercontent.com/assets/130362/19538186/e8152a20-9620-11e6-83f8-242430fc14ac.png)

I had to look at the code (https://github.com/senchalabs/connect/blob/master/index.js#L189-L213) to find out that this function takes other arguments, what these arguments are, and what their default arguments are.

**Comment by dougwilson** [comment]
Which arguments in particular? The source code you highlighted shows even less than the screenshot you provided of the README.

**Comment by zodiac** [comment]
@dougwilson I was referring to this

![image](https://cloud.githubusercontent.com/assets/130362/19540712/5df247d8-962f-11e6-9534-2c9988eec5e6.png)

This brought me here: https://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback. I was trying to find out which host connect binds to and how to change it.

**Comment by dougwilson** [comment]
Oh, haha, didn't see that. Yes, I can copy that sentence into the README.

**Comment by zodiac** [comment]
Thanks for being receptive.

Does the project have API docs? That was the first place I tried looking for `app.listen` documentation.

A few other documentation comments for this section:

`http.Server#listen` has 3 rather different signatures, shown bellow

![image](https://cloud.githubusercontent.com/assets/130362/19541082/bae291f8-9631-11e6-9573-e7e20b4fa052.png)

From the implementation I think all 3 forms can be used but I'm not sure, I've only seen examples use the last (highlighted) form.

Also, I think this section

![image](https://cloud.githubusercontent.com/assets/130362/19541145/39f7b5cc-9632-11e6-8c9b-d64ee412cdfe.png)

should call `server.lister(...)` on the next line, since the `app.listen` example both starts the server (internally) and listens to a port.

I can open a PR with suggested changes addressing these if you want

**Comment by dougwilson** [comment]
Cool; I added the note to the section, which seemed to be what the issue was about, so I noted this issue in the commit message, causing the issue to close automatically).

> From the implementation I think all 3 forms can be used but I'm not sure, I've only seen examples use the last (highlighted) form.

It accepts all three; the note I added explains it's identical to the `listen` method on `http.Server`, which implies this. Since what this does varies on the version of Node.js you are using, it is very difficult to document this I our README, because you can't just document all the different `listen` signatures in the current Node.js version, but probably in all Node.js versions.

> should call server.lister(...) on the next line, since the app.listen example both starts the server (internally) and listens to a port.

I think you're missing the point of that section. It's just explaining that you can pass `app` to `createServer`, and showing the example. It is not meant to show anything else but that exact one thing.

> Also, does the project have API docs? That was the first place I tried looking for app.listen documentation.

This project has almost no API. The only documentation is the README.
