### ISSUE TITLE
Settle on `res.locals` as mechanism for sharing config between middleware

### ISSUE THREAD

**Issue by brettz9** [senchalabs/connect#1117]
May I suggest settling on `res.locals` as an official `connect`-approved way of passing on config? I know it is part of Express, but this seems to me to be of generic enough applicability to be encoded as part of `connect` itself... I presume you'd just need `connect` to define the object?

**Comment by dougwilson** [comment]
I'm not really sure what would be required here? Just add a middleware that sets res.locals to whatever value you want and then use it later?

Unlike Express, the res object is just whatever is passed in and does not have any properties outside of what was passed in (typically what comes with Node.js), as connect is a module to connect muddleware together (hence it's name).

Perhaps if you could show what you think the changes to connect should be?

**Comment by brettz9** [comment]
As far as behavior, I guess just setting an empty object would be an ideal, as it would obviate the need for middleware needing to check for its existence and set an empty object if not yet exsiting.

But my main concern is less about adding any behavior and just seeing it documented as a recommended way to pass around config that can be shared between middleware.

**Comment by dougwilson** [comment]
Well, documentation consists only about the functionality this module actually implements / adds, and thus one would need to have documented to understand how it works. Since this module does nothing with `res.locals`, What, exactly, would the documentation state in it? That you can set it and use it? I mean, you can do that with any property at all.

**Comment by brettz9** [comment]
Take a look at https://stackoverflow.com/questions/18875292/passing-variables-to-the-next-middleware-using-next-in-express-js . While this is about Express, I think it shows an interest in, and confusion about, how to pass on shared config. There are 148 up-votes for an undocumented approach (292 votes for the recommended).

And projects do document recommended practices for use of their library even when they don't enforce or use it. But despite my greater interest in standard documentation (aiding one to more quickly introspect on existing config it is more predictably in one place), setting `res.locals` to an empty object would indeed be useful.

**Comment by dougwilson** [comment]
In Express.js, the `res.locals` is only meant to usage to store data to provide to your view layer in `res.render` -- using it as a generic storage mechanism is beyond what it was designed for, and would be abusing It as well. If that is what you're saying you want it for, then I definately wouldn't want it documented as that, because the Express.js `res.locals` was never meant as a generic method to pass variables between middlewares at all.

**Comment by brettz9** [comment]
Ok, good to know. Would be nice to have *some* recommended mechanism, but obviously your call.

**Comment by dougwilson** [comment]
The purpose of this module is to not have a recommended mechanism that falls outside the scope of the modules. This is where the "unopinionated" tag line comes from in Express.js -- you can decide how you want to pass variables around between your onw middleware. If you're using third-party middleware, their documentation should describe how they expect data passed to them.

There is an obvious downside to not having an opinion here -- that there is more than one way to do it, but that is what the Express.js (and Connect, which was it's predecessor) was built around. There are other frameworks that will provide rigidity if that's what you're looking to have instead.

**Comment by brettz9** [comment]
I don't see "recommended" the same as opinionated enforcement. But I hear you.
