### ISSUE TITLE
Accepts array for middleware

### ISSUE THREAD

**Issue by brettz9** [senchalabs/connect#1118]
Would you accept an updated PR along the lines of #808 to allow an array of middleware to `use`? I think it is not reasonable to delegate this to wrapping libraries which may either become out of sync or are bloated relative to `connect`. This is just some simple sugar to avoid repeating oneself but a must-have imo... Wrapping libraries can add fancier APIs, but I think this one is really necessary for a sleek, clean, modern API...

**Comment by dougwilson** [comment]
The reason this was removed is because this kind of sugar was left to Express in the Connect/Express split.

If you want that sugar use Express. If you want zero sugar, use Connect.

**Comment by brettz9** [comment]
This just strikes me as being dogmatic to the detriment of the one main function of the project--being able to conveniently add multiple middleware (where middleware is itself a form of convenience).

To me, it is Java ugliness rather than JavaScript elegance, and forcing an unnecessary choice. But, hey, it's obviously your call...

**Comment by dougwilson** [comment]
It's the entire team's call. The issue you referenced I didn't even comment in, so I am not the sole operator here.

**Comment by brettz9** [comment]
Sorry, I wasn't trying to make this personal or at all intemperate. I just mean "your" in the collective sense.

It was just my hope that some things could be open for revisiting. The browsers tend to act these days on the approach of yes, starting with a simple API, and seeing what libraries come up with on top of the APIs, but then later picking up some of the most useful ones to standardize on to add into core--even if while these features can be implemented with libraries (e.g., `document.querySelector`).

**Comment by dougwilson** [comment]
This project is the bare bones as it is designed. All the APIs that were picked up because they were useful to someone were added to the project known as "express". Your exact want of accepting array in .use is an express for example.

If what everyone wanted was added to connect, then connect would just be express. There are two projects so if someone wants the bare bones and only wants to add the sugar they want, they can start somewhere (connect) but they also have a module that had all the sugar people wanted added (express).

There is nothing to reconsider; the API was already added and that's why it is in express.
