### ISSUE TITLE
Support route patterns

### ISSUE THREAD

**Issue by sz-cgt** [senchalabs/connect#1121]
Why doesn't connect support regexp definitions for routes? 

For example: app.use(/\\/path[1234]/, handler)

I really like the lightweight, low dependency nature of connect, but find myself writing lots of boilerplate logic to handle different route selects that I could avoid with routes as regular expressions instead of straight strings.

If the idea is of interest, I'm happy to create a pull request that adds the feature.

**Comment by dougwilson** [comment]
Hi @sz-cgt the reason it doesn't is because that's what keep it lightweight -- by excluding features. You really have three methods (though I'm sure there are many more) to get this:

1. Use a more full-features framework like Express. This would assume your definition of "lightweight" means less direct dependencies for you.
2. Use connect in conjunction with a router that supports the added feature you need. For example the `router` module.
3. Create a helper glue that does just want you wait and use that (so like a subset of the `router` module).

I hope that helps!
